config/routes.rb
Scheduler::Application.routes.draw do
  namespace :api do
    resources :jobs do
      collection do
        get :scheduled
        get :processing
        get :on_hold
        get :success
        get :completed
        get :failed
        delete :purge
      end

      member do
        post :retry
      end

      member do
        resources :state_changes
        resources :notifications
      end
    end

    get '/probe'   => 'api#probe'
    get '/schedule' => 'scheduler#schedule'

    resources :presets

    resources :hosts

    get '/statistics' => 'statistics#show'
  end

  resources :jobs

  resources :presets, :hosts

  root :to => 'dashboard#show'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @history = History.new(params[:period])

    recent_jobs = Job.recents.limit(10)

    @scheduled_jobs  = recent_jobs.scheduled
    @processing_jobs = recent_jobs.processing
    @failed_jobs     = recent_jobs.failed
  end
end

app/views/dashboard/_history.html.erb
<div id="history">
	<ol class="nav">
		<% selected = @history.period %>
		<li class="<%= 'selected' if selected == 'today' %>">
			<%= link_to_unless selected == 'today', 'Today', url_for(params.merge(:period => 'today')) %>
		</li>
		<li class="<%= 'selected' if selected == 'yesterday' %>">
			<%= link_to_unless selected == 'yesterday', 'Yesterday', url_for(params.merge(:period => 'yesterday')) %>
		</li>
		<li class="<%= 'selected' if selected == 'week' %>">
			<%= link_to_unless selected == 'week', 'This Week', url_for(params.merge(:period => 'week')) %>
		</li>
		<li class="<%= 'selected' if selected == 'month' %>">
			<%= link_to_unless selected == 'month', 'This Month', url_for(params.merge(:period => 'month')) %>
		</li>
		<li class="<%= 'selected' if selected == 'all' %>">
			<%= link_to_unless selected == 'all', 'All', url_for(params.merge(:period => 'all')) %>
		</li>
	</ol>
	<table>
		<tr>
			<th><%= link_to 'Completed', completed_jobs_path %></th>
			<th><%= link_to 'Failed', failed_jobs_path %></th>
			<th>Time encoded</th>
			<th>Average processing time</th>
			<th>Average queue time</th>
		</tr>
		<tr>
			<td class="success" title="<%= @history.completed_jobs.size %> out of <%= @history.jobs.size %> completed">
				<%= @history.completed_jobs.size %>
			</td>
			<td class="failed" title="<%= @history.failed_jobs.size %> out of <%= @history.jobs.size %> failed">
				<%= @history.failed_jobs.size %>
			</td>
			<td title="<%= number_with_delimiter @history.seconds_encoded %> seconds">
				<%= number_to_time @history.seconds_encoded %>
			</td>
			<td title="<%= number_with_delimiter @history.average_processing_time %> seconds">
				<%= number_to_time @history.average_processing_time %>
			</td>
			<td title="<%= number_with_delimiter @history.average_queue_time %> seconds">
				<%= number_to_time @history.average_queue_time %>
			</td>
		</tr>
	</table>
</div>

app/views/dashboard/show.html.erb
<% title 'Dashboard' %>

<%= section 'History' do %>
  <%= render "history" %>
<% end %>

<%= section 'Recently scheduled jobs' do %>
  <%- if @scheduled_jobs.any? -%>
  	<% @jobs = @scheduled_jobs %>
  	<%= render "/jobs/jobs" %>
  <%- else -%>
  	<p>No recently scheduled jobs.</p>
  <%- end -%>
<% end %>
  
<%= section 'Recently processing jobs' do %>
  <%- if @processing_jobs.any? -%>
  	<% @jobs = @processing_jobs %>
  	<%= render "/jobs/jobs" %>
  <%- else -%>
  	<p>No recently processing jobs</p>
  <%- end -%>
<% end %>
  
<%= section 'Recently failed jobs' do %>
  <%- if @failed_jobs.any? -%>
  	<% @jobs = @failed_jobs %>
  	<%= render "/jobs/jobs" %>
  <%- else -%>
  	<p>No recently failed jobs</p>
  <%- end -%>
<% end %>
  
<div class="form-actions">
  <%= link_to 'View all jobs', jobs_path, class: 'btn btn-small btn-primary' %>
</div>